title: Диффузия
description: В данном параграфе исследуется распространение частиц газа в объеме --- диффузия.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
