title: Частицы в электромагнитном поле.
description: О поведении частиц в электромагнитном поле.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
