title: Фнутреняя энергия. Фотонный газ.
description: О понятии внутренней энергии и степенях свободы. Также приведены свойства фотонного газа.
authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
