title: Теплопроводность
description: В данном параграфе исследуется распространение тепла в объеме газа --- теплопроводность.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
