title: Параметры газа и смеси газов
description: О том, какие параметры есть у газов и их свойства для смесей.
authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
