title: Распад ядер. Ядерные реакции.
description: О законе распада и ядерных реакциях.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
