title: Уравнение состояния идеального газа
description: Главное уравнение, связывающее между собой параметры газа.
authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
