title: Уравнение состояния идеального газа
description: Как связаны основные параметры газа
authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
