title: Фазовое пространство. Статвес. Энтропия.
description: Понятие фазового пространства это краеугольный камень статистической физики. Оно позволяет ввести фундаментальные понятия статистического веса и энтропии, на которых строится большая часть выводов статистических распределений.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
