title: Распределение скоростей и температура
description: В данном разделе рассказанову

authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
