title: Модель Томсона. Томсоновское рассеяние.
description: Одна из первых успешных моделей атомов.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
