title: Частицы стандартной модели
description: Обзор частиц и взаимодействий, описываемых современной физикой.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
