title: Распределение скоростей и температура
description: О понятии функции распределения и температуры.

authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
