title: Первое начало термодинамики. Адиабатический процесс. Теплоемкость.
description: О понятии работы, теплоты и их связи с внутренней энергией. Также вводится адиабатический процесс, обсуждаются его свойства. Вводится понятие теплоемкости.

authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
