title: Циклотронное и синхротронное излучение.
description: Об излучении движущимися в магнитном поле частиц.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
