title: Параметры газа и смеси газов
description: О том, что такое газ и какие существуют параметры у газов. Также показано, как параметры смеси газов выражаются через параметры компонент смеси.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
