title: Изотермическая атмосфера. Распределение Больцмана.
description: В этом параграфе описывается модель атмосферы постоянной температуры, которая очень важна для физики. Она напрямую связана с распределением Больцмана, которое описывает поведение частиц газа в термодинамическом равновесии в присутсвии внешнего поля.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
