title: Уравнение состояния идеального газа
description: Об уравнении состояния идеального газа - оснонвном соотношении, связывающем параметры газа.
authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
