title: Уравнение состояния идеального газа
description: В данном параграфе получено уравнение состояния идеального газа --- основное соотношение, связывающее его главные параметры.
authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
