title: Эффект Зеемана.
description: Эффект Зеемана в рамках классической физики.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
