title: Распределения Ферми и Бозе
description: Распределение Гиббса это центральное понятие статистической физики, предсказывающее заполнение энергетических уровней системы в совершенно разных ситуациях. Пройденные ранее распределения Максвелла и Больцмана являются лишь частными случаями этого распределения.
authors:
  - Василий Муратов
order: 3
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
