title: Уравнение гидростатического равновесия
description: Об одном из важнейших уравнений в астрофизике, описывающее равновесный газ во внешнем поле.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
