title: Излучение движущимися частицами. Радиационное трение.
description: Об излучении света ускоряющимися частицами. Сила радиационного трения.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
