title: Распределение скоростей и температура
description: В данном разделе вводится понятие распределения скоростей для частиц газа. Также определена температура.

authors:
  - Василий Муратов
order: 10
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
