title: Распределение Гиббса
description: Распределение Гиббса это центральная формула статистической физики, предсказывающая заполнение энергетических уровней системы в совершенно разных ситуациях. Пройденные ранее распределения Максвелла и Больцмана являются лишь частными случаями этого распределения.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
