title: Движение заряженных частиц во внешнем поле.
description: О законах движения заряженных частиц во внешнем ЭМП.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
