title: Колебания с трением в физике и математике.
description: Уравнение свободных и вынужденных колебаний в физике. Их решение.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
