title: Распределения Гиббса, Ферми и Бозе
description: В этой главе изложены принципы продвинутой статистической физики --- фундаментальное понятие распределения Гиббса, а также выведены важнейшие в астрофизике распределения для квантовых газов.
