title: Столкновения частиц
description: До этого мы практически не занимались вопросами столкновения частиц, поскольку рассматривали идеальные газы. В данном параграфе изложены базовые понятия теории столкновений --- сечение, длина свободного пробега итд.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
