title: Распределение Максвелла
description: Распределение Максвелла решает одну из естественных задач физики --- с какой вероятностью частицы хаотически движущегося газа имеют данный модуль и направление скорости.
authors:
  - Василий Муратов
order: 3
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
