title: Внутреняя энергия. Фотонный газ.
description: О понятии внутренней энергии и степенях свободы. Также приведены свойства фотонного газа.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
