title: Фотоны. Квантовые законы излучения Эйнштейна.
description: О квантах электромагнитного поля итд.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
