title: Что такое свет?
description: Что в физике называется волнами? Электромагнитные волны.
authors:
  - Василий Муратов
blocks:
  theory:
    authors: [Василий Муратов]
  methods:
    authors: [Василий Муратов]
